FROM fedora
 

WORKDIR /pacman

RUN dnf -y install npm jq  && dnf clean all && npm install mongodb    
 
COPY . /pacman  
RUN chmod -R 777  /pacman
RUN npm install 
 
EXPOSE 8080 
COPY  pacman.sh /usr/local/bin/
RUN dnf -y install dos2unix
RUN dos2unix /usr/local/bin/pacman.sh && chmod +x /usr/local/bin/pacman.sh

ENTRYPOINT ["pacman.sh"]
